### ISSUE TITLE
Intro to ZenHub

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-public-reporting#19]
#### Description:
Prepare and deliver ZenHub training for our Public Reporting SMEs to help facilitate communication, transparency and inclusion in our work and process related to the public reporting project.

#### Checklist:
- [x] Design training material
- [x] Get SMEs to create GitHub account (if not already done)
- [x] Set up meeting with SMEs to facilitate training
- [x] Conduct training session (May 9, 2022)

#### Notes:

**Comment by LindsayMacfarlane** [comment]
@jaimiebutton - noticing this ticket got moved to icebox, is this correct? Do we want it in design backlog? We should also loop in @Sriram-pc to design and deliver the training to public reporting staff.

**Comment by LindsayMacfarlane** [comment]
@jaimiebutton - when would we like to action this training - next sprint?

**Comment by LindsayMacfarlane** [comment]
@Sriram-pc - as discussed during our check-in, let's get this scheduled and into ES's calendar asap.

**Comment by LindsayMacfarlane** [comment]
@Sriram-pc - thank you for drafting the ZenHub training. I've left comments and feedback on the Miro board.

**Comment by Sriram-pc** [comment]
@LindsayMacfarlane I have made changes based on the comments. Also added comments to the miroboard. I will be moving this Zenhub session to the Public reporting thinking MiroBoard. Thanks.

**Comment by LindsayMacfarlane** [comment]
Hi @Sriram-pc - Thank you for facilitating the ZenHub traning. Were there any follow up or lessons learned from today's session?

**Comment by Sriram-pc** [comment]
Hi @LindsayMacfarlane Feedback from Emilie was positive and good. With respect to parking lot "Questions", "Feedback" no specific feedback or questions. 
I have added one feedback stickie based on the feedback that she would like to keep the Zenhub training info in the Public Reporting Thinking MiroBoard so that she can refer in future.
I have also asked her to reach out to any of us in case if she has any questions related to Zenhub.
Please let me know if any other action is required.
Thanks Jaimie and you for help me setting up the training board.

**Comment by LindsayMacfarlane** [comment]
Thanks everyone for your work and collaboration on this one :)
